### ISSUE TITLE
@types/react dependency

### ISSUE THREAD

**Issue by herecydev** [vadimdemedes/ink-spinner#10]
@types/react is [included as a dependency](https://github.com/vadimdemedes/ink-spinner/blob/master/package.json#L35). Is that intentional? I would have expected this only as a devDependency

**Comment by vadimdemedes** [comment]
Not intentional, will fix.

**Comment by vadimdemedes** [comment]
Fixed in [`4.0.1`](https://github.com/vadimdemedes/ink-spinner/releases/tag/v4.0.1).
