### ISSUE TITLE
Cannot read property 'dots' of undefined

### ISSUE THREAD

**Issue by GiladShoham** [vadimdemedes/ink-spinner#12]
Since 2 days ago, I'm getting an error when using the Spinner in a very simple way
`<Spinner type="dots" />`

This might be a result of a new release of the cli-spinners 2 days ago - see https://www.npmjs.com/package/cli-spinners

It seems that it should work now without the `default`. so
if I'm changing `const spinner = cli_spinners_1.default[type];`  to `const spinner = cli_spinners_1[type];` it works

```bash
  ERROR  Cannot read property 'dots' of undefined

 10: const Spinner = ({ type = 'dots' }) => {
 11:     const [frame, setFrame] = react_1.useState(0);
 12:     console.log('cli_spinners_1', cli_spinners_1)
 13:     const spinner = cli_spinners_1.default[type];
 14:     // const spinner = cli_spinners_1[type];
 15:     react_1.useEffect(() => {
 16:         const timer = setInterval(() => {
```

**Comment by kozaktomas** [comment]
This might be the problem: https://github.com/sindresorhus/cli-spinners/commit/c9f3e131d555667c3bdaf064c874d6ade5359065

btw, released in v2.6.1

**Comment by dankrajnak** [comment]
Made a PR: https://github.com/vadimdemedes/ink-spinner/pull/13

I would also suggest removing yarn.lock from .gitignore so this kind of thing doesn't happen in the future.

**Comment by thejustinwalsh** [comment]
Oh dang, so this is the issue, I went to the source first... haha
https://github.com/sindresorhus/cli-spinners/issues/57

Though doesn't this actually indicate that the cli-spinners package had more than a patch change contained within it?

**Comment by sindresorhus** [comment]
> I would also suggest removing yarn.lock from .gitignore so this kind of thing doesn't happen in the future.

That would make no difference. Yarn.lock is not used when you install a package.

**Comment by alcance** [comment]
Glad i found this issue. Just started usIng Blitz and haven't found a clear workaround for this. Already tried installing canary version but keep getting same error and not sure how to overcome this blocking issue. Can anyone point me to a solution? Thanks!

`"blitz": "0.39.0",`
