### ISSUE TITLE
Typescript definitions out-of-sync with Ink v2

### ISSUE THREAD

**Issue by john-osullivan** [vadimdemedes/ink-spinner#6]
Hey, I just did a fresh install and found that the `@types/ink-spinner` definitions are out of date!  They still reflect the Ink 1 setup where it had a dedicated `<Component />` class.

I made a PR which updates that import to instead come from React.  Made this change in my own project first, it works just fine.  Wanted to give you a heads up here in case you're more likely to notice it 👍 

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38445

**Comment by vadimdemedes** [comment]
Thank you! Would you be able to move type definitions into this repository instead?

**Comment by john-osullivan** [comment]
Hey, I just looked back at this -- that would be my pleasure!  I'll link here once I've got a PR.

**Comment by vadimdemedes** [comment]
Fixed in `master`, since `ink-spinner` was rewritten in TS.
